### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sylvestreee** [sylvestreee/ArchiDevWeb#2]
# Fonctionnalités

- [x] Affichage d'une page produit
- [x] Barre de recherche
- [x] Filtrage
- [x] Ajout des meilleures ventes
- [x] Ajout du genre dans la recheche
- [x] Ajout du genre dans le filtrage
- [x] Inscription
- [x] Déconnexion
- [x] Connexion
- [x] Ajout d'un jeu au panier
- [x] Suppression d'un jeu du panier
- [x] Modification du compte
